"""Create NordicIntel metadata and harvest schema

Revision ID: 0001_initial
Revises: 
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('adapter_type', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('secret_refs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("adapter_type ~ '^[a-z0-9][a-z0-9._-]*$'", name=op.f('provider_adapter_type_check')),
    sa.CheckConstraint("id ~ '^[a-z0-9][a-z0-9._-]*$'", name=op.f('provider_id_check')),
    sa.CheckConstraint("jsonb_typeof(config) = 'object'", name=op.f('provider_config_check')),
    sa.CheckConstraint("jsonb_typeof(secret_refs) = 'object'", name=op.f('provider_secret_refs_check')),
    sa.CheckConstraint("region IS NULL OR region ~ '^[A-Z]{2}$'", name=op.f('provider_region_check')),
    sa.CheckConstraint('length(label) > 0', name=op.f('provider_label_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_pkey'))
    )
    op.create_table('dataset',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=False),
    sa.Column('native_table_id', sa.Text(), nullable=False),
    sa.Column('serving_mode', sa.Text(), server_default=sa.text("'routed'"), nullable=False),
    sa.Column('retired', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('operator_disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('availability_status', sa.Text(), server_default=sa.text("'available'"), nullable=False),
    sa.Column('failed_languages', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('last_error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_harvested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability_status IN ('available', 'unavailable')", name=op.f('dataset_availability_status_check')),
    sa.CheckConstraint("id ~ '^[a-z0-9][a-z0-9._-]*$'", name=op.f('dataset_id_check')),
    sa.CheckConstraint("last_error IS NULL OR jsonb_typeof(last_error) = 'object'", name=op.f('dataset_last_error_check')),
    sa.CheckConstraint("serving_mode IN ('routed')", name=op.f('dataset_serving_mode_check')),
    sa.CheckConstraint('length(native_table_id) > 0', name=op.f('dataset_native_table_id_check')),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('dataset_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dataset_pkey')),
    sa.UniqueConstraint('provider_id', 'native_table_id', name=op.f('dataset_provider_id_native_table_id_key'))
    )
    op.create_index('dataset_provider_idx', 'dataset', ['provider_id', 'id'], unique=False)
    op.create_table('harvest_job',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('request_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_backend_pid', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("error IS NULL OR jsonb_typeof(error) = 'object'", name=op.f('harvest_job_error_check')),
    sa.CheckConstraint("jsonb_typeof(request) = 'object'", name=op.f('harvest_job_request_check')),
    sa.CheckConstraint("status <> 'failed' OR error IS NOT NULL", name=op.f('harvest_job_failure_error_check')),
    sa.CheckConstraint("status <> 'running' OR (started_at IS NOT NULL AND heartbeat_at IS NOT NULL AND owner_backend_pid IS NOT NULL)", name=op.f('harvest_job_running_state_check')),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'cancelled')", name=op.f('harvest_job_status_check')),
    sa.CheckConstraint("status NOT IN ('completed', 'failed', 'cancelled') OR finished_at IS NOT NULL", name=op.f('harvest_job_terminal_state_check')),
    sa.CheckConstraint("trigger IN ('manual', 'schedule')", name=op.f('harvest_job_trigger_check')),
    sa.CheckConstraint('request_key IS NULL OR length(request_key) BETWEEN 1 AND 200', name=op.f('harvest_job_request_key_check')),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('harvest_job_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('harvest_job_pkey')),
    sa.UniqueConstraint('request_key', name=op.f('harvest_job_request_key_key'))
    )
    op.create_index('harvest_job_one_running_provider_idx', 'harvest_job', ['provider_id'], unique=True, postgresql_where=sa.text("status = 'running'"))
    op.create_index('harvest_job_provider_history_idx', 'harvest_job', ['provider_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('harvest_job_queue_idx', 'harvest_job', ['created_at', 'id'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index('harvest_job_stale_idx', 'harvest_job', ['heartbeat_at'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_table('harvest_schedule',
    sa.Column('provider_id', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('every_seconds', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("jsonb_build_object('table_id', NULL, 'force', false, 'languages', NULL)"), nullable=False),
    sa.CheckConstraint("jsonb_typeof(request) = 'object' AND request->'table_id' = 'null'::jsonb", name=op.f('harvest_schedule_request_check')),
    sa.CheckConstraint('every_seconds > 0', name=op.f('harvest_schedule_every_seconds_check')),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('harvest_schedule_provider_id_fkey')),
    sa.PrimaryKeyConstraint('provider_id', name=op.f('harvest_schedule_pkey'))
    )
    op.create_index('harvest_schedule_due_idx', 'harvest_schedule', ['next_run_at'], unique=False, postgresql_where=sa.text('enabled'))
    op.create_table('dataset_alias',
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default=sa.text("'native'"), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("length(alias) > 0 AND position('/' in alias) = 0", name=op.f('dataset_alias_alias_check')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name=op.f('dataset_alias_validity_check')),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('dataset_alias_dataset_id_fkey')),
    sa.PrimaryKeyConstraint('alias', name=op.f('dataset_alias_pkey'))
    )
    op.create_table('dataset_metadata',
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_code', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('updated', sa.Text(), nullable=False),
    sa.Column('first_period', sa.Text(), nullable=False),
    sa.Column('last_period', sa.Text(), nullable=False),
    sa.Column('variable_names', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('discontinued', sa.Boolean(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('subject_code', sa.Text(), nullable=True),
    sa.Column('time_unit', sa.Text(), nullable=True),
    sa.Column('paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('href', sa.Text(), nullable=True),
    sa.Column('link', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('note_mandatory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('px', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparison_marker', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_harvested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_document', postgresql.TSVECTOR(), server_default=sa.text("''::tsvector"), nullable=False),
    sa.CheckConstraint("category IN ('internal', 'public', 'private', 'section')", name=op.f('dataset_metadata_category_check')),
    sa.CheckConstraint("comparison_marker IS NULL OR jsonb_typeof(comparison_marker) = 'object'", name=op.f('dataset_metadata_comparison_marker_check')),
    sa.CheckConstraint("contacts IS NULL OR jsonb_typeof(contacts) = 'array'", name=op.f('dataset_metadata_contacts_check')),
    sa.CheckConstraint("jsonb_typeof(links) = 'array'", name=op.f('dataset_metadata_links_check')),
    sa.CheckConstraint("jsonb_typeof(roles) = 'object' AND roles - ARRAY['time', 'geo', 'metric'] = '{}'::jsonb", name=op.f('dataset_metadata_roles_check')),
    sa.CheckConstraint("link IS NULL OR jsonb_typeof(link) = 'object'", name=op.f('dataset_metadata_link_check')),
    sa.CheckConstraint("note_mandatory IS NULL OR jsonb_typeof(note_mandatory) = 'object'", name=op.f('dataset_metadata_note_mandatory_check')),
    sa.CheckConstraint("paths IS NULL OR jsonb_typeof(paths) = 'array'", name=op.f('dataset_metadata_paths_check')),
    sa.CheckConstraint("px IS NULL OR jsonb_typeof(px) = 'object'", name=op.f('dataset_metadata_px_check')),
    sa.CheckConstraint("time_unit IN ('Annual', 'Quarterly', 'Monthly', 'Weekly', 'Other')", name=op.f('dataset_metadata_time_unit_check')),
    sa.CheckConstraint('length(first_period) > 0', name=op.f('dataset_metadata_first_period_check')),
    sa.CheckConstraint('length(label) > 0', name=op.f('dataset_metadata_label_check')),
    sa.CheckConstraint('length(language) > 0 AND language = lower(btrim(language))', name=op.f('dataset_metadata_language_check')),
    sa.CheckConstraint('length(last_period) > 0', name=op.f('dataset_metadata_last_period_check')),
    sa.CheckConstraint('length(updated) > 0', name=op.f('dataset_metadata_updated_check')),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('dataset_metadata_dataset_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'language', name=op.f('dataset_metadata_pkey'))
    )
    op.create_index('dataset_metadata_search_idx', 'dataset_metadata', ['search_document'], unique=False, postgresql_using='gin')
    op.create_table('harvest_item',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('source_table_id', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("error IS NULL OR jsonb_typeof(error) = 'object'", name=op.f('harvest_item_error_check')),
    sa.CheckConstraint("status <> 'failed' OR error IS NOT NULL", name=op.f('harvest_item_failure_error_check')),
    sa.CheckConstraint("status = 'running' OR finished_at IS NOT NULL", name=op.f('harvest_item_terminal_state_check')),
    sa.CheckConstraint("status IN ('running', 'updated', 'skipped', 'failed')", name=op.f('harvest_item_status_check')),
    sa.CheckConstraint('length(source_table_id) > 0', name=op.f('harvest_item_source_table_id_check')),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('harvest_item_dataset_id_fkey')),
    sa.ForeignKeyConstraint(['job_id'], ['harvest_job.id'], name=op.f('harvest_item_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('harvest_item_pkey')),
    sa.UniqueConstraint('job_id', 'source_table_id', name=op.f('harvest_item_job_id_source_table_id_key'))
    )
    op.create_index('harvest_item_dataset_idx', 'harvest_item', ['dataset_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('harvest_item_job_idx', 'harvest_item', ['job_id', 'status', 'id'], unique=False)
    op.create_table('dimension',
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('notes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('extension', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('link', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('index >= 0', name=op.f('dimension_index_check')),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('dimension_code_check')),
    sa.ForeignKeyConstraint(['dataset_id', 'language'], ['dataset_metadata.dataset_id', 'dataset_metadata.language'], name=op.f('dimension_dataset_id_language_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'language', 'code', name=op.f('dimension_pkey')),
    sa.UniqueConstraint('dataset_id', 'language', 'index', name=op.f('dimension_dataset_id_language_index_key'))
    )
    op.create_table('category',
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('dimension_code', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('notes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('child', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('unit', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('index >= 0', name=op.f('category_index_check')),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('category_code_check')),
    sa.ForeignKeyConstraint(['dataset_id', 'language', 'dimension_code'], ['dimension.dataset_id', 'dimension.language', 'dimension.code'], name=op.f('category_dataset_id_language_dimension_code_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'language', 'dimension_code', 'code', name=op.f('category_pkey')),
    sa.UniqueConstraint('dataset_id', 'language', 'dimension_code', 'index', name=op.f('category_dataset_id_language_dimension_code_index_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('dimension')
    op.drop_index('harvest_item_job_idx', table_name='harvest_item')
    op.drop_index('harvest_item_dataset_idx', table_name='harvest_item')
    op.drop_table('harvest_item')
    op.drop_index('dataset_metadata_search_idx', table_name='dataset_metadata', postgresql_using='gin')
    op.drop_table('dataset_metadata')
    op.drop_table('dataset_alias')
    op.drop_index('harvest_schedule_due_idx', table_name='harvest_schedule', postgresql_where=sa.text('enabled'))
    op.drop_table('harvest_schedule')
    op.drop_index('harvest_job_stale_idx', table_name='harvest_job', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('harvest_job_queue_idx', table_name='harvest_job', postgresql_where=sa.text("status = 'queued'"))
    op.drop_index('harvest_job_provider_history_idx', table_name='harvest_job')
    op.drop_index('harvest_job_one_running_provider_idx', table_name='harvest_job', postgresql_where=sa.text("status = 'running'"))
    op.drop_table('harvest_job')
    op.drop_index('dataset_provider_idx', table_name='dataset')
    op.drop_table('dataset')
    op.drop_table('provider')
    # ### end Alembic commands ###
